apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: soundcheck.demo
  description: Soundcheck Demo Component
  annotations:
    pagerduty.com/integration-key: dsadsadsadsadsadsa
    sonarqube.org/project-key: local-sq/test-project-key
  tags:
    - github
spec:
  type: service
  lifecycle: production
  owner: toast-infra
  system: soundcheck
